apiVersion: v1
kind: ConfigMap
metadata:
  name: cachepuppy-config
  namespace: cachepuppy
data:
  PHX_SERVER: "true"
  PORT: "4000"
  PHX_HOST: "cachepuppy.yourdomain.com"
  CACHEPUPPY_RUNTIME: "kubernetes"
  RELEASE_DISTRIBUTION: "name"
  LIBCLUSTER_NODE_BASENAME: "cachepuppy_core"
  LIBCLUSTER_K8S_SERVICE: "cachepuppy-headless"
  LIBCLUSTER_POLLING_INTERVAL_MS: "5000"
  ERL_AFLAGS: "-kernel inet_dist_listen_min 9100 inet_dist_listen_max 9100"
  AUTH_ENABLED: "true"
  JWT_IDENTITY_CLAIM: "sub"
  CACHE_SNAPSHOT_INTERVAL_MS: "300000"
