apiVersion: v1
kind: Secret
metadata:
  name: cachepuppy-secrets
  namespace: cachepuppy
type: Opaque
data:
  release-cookie: <base64-value>
  secret-key-base: <base64-value>
  jwt-secret: <base64-value>
