apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cachepuppy.configMapName" . }}
  namespace: {{ include "cachepuppy.namespace" . }}
  labels:
    {{- include "cachepuppy.labels" . | nindent 4 }}
data:
  PHX_SERVER: "true"
  PORT: "4000"
  PHX_HOST: {{ .Values.config.phxHost | quote }}
  CACHEPUPPY_RUNTIME: {{ .Values.config.cachepuppyRuntime | quote }}
  RELEASE_DISTRIBUTION: {{ .Values.config.releaseDistribution | quote }}
  LIBCLUSTER_NODE_BASENAME: {{ .Values.config.libclusterNodeBasename | quote }}
  LIBCLUSTER_K8S_SERVICE: {{ include "cachepuppy.headlessServiceName" . | quote }}
  LIBCLUSTER_POLLING_INTERVAL_MS: {{ .Values.config.libclusterPollingIntervalMs | quote }}
  ERL_AFLAGS: {{ .Values.config.erlAflags | quote }}
  AUTH_ENABLED: {{ .Values.config.authEnabled | quote }}
  JWT_IDENTITY_CLAIM: {{ .Values.config.jwtIdentityClaim | quote }}
  CACHE_SNAPSHOT_INTERVAL_MS: {{ .Values.config.cacheSnapshotIntervalMs | quote }}
  {{- with .Values.config.cacheStorageDir }}
  CACHE_STORAGE_DIR: {{ . | quote }}
  {{- end }}
