apiVersion: v1
kind: Service
metadata:
  name: {{ include "cachepuppy.headlessServiceName" . }}
  namespace: {{ include "cachepuppy.namespace" . }}
  labels:
    {{- include "cachepuppy.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "cachepuppy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 4000
      targetPort: http
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: dist
      port: 9100
      targetPort: dist
